/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Posts;

/**
 *
 * @author Pedro
 */
public class FrmPosts extends javax.swing.JPanel {
    private GestorVistaPosts gestorPosts;
    /**
     * Creates new form
     */
    public FrmPosts() {
        initComponents();
    }

    FrmPosts(GestorVistaPosts gestor) {
        try{
           initComponents();
           }
           catch(Exception e){
            
        }  
        this.setGestorPosts(gestor);
    }

    public GestorVistaPosts getGestorPosts() {
        return gestorPosts;
    }

    public void setGestorPosts(GestorVistaPosts gestorPosts) {
        this.gestorPosts = gestorPosts;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
