/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Posts;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Pedro
 */
public class FrmPost extends javax.swing.JInternalFrame {
    private GestorVistaPosts gestorPosts;
    
    /**
     * Creates new form FrmPost
     */
    public FrmPost() {
        initComponents();
    }
    FrmPost(GestorVistaPosts gestor) {
        try{
           initComponents();
           }
           catch(Exception e){
            
        }  
        this.setGestorPosts(gestor);
    }

    public GestorVistaPosts getGestorPosts() {
        return gestorPosts;
    }

    public void setGestorPosts(GestorVistaPosts gestorPosts) {
        this.gestorPosts = gestorPosts;
    }
    public void getData() throws IOException{
        this.getGestorPosts().getData();
    }

    public JTextArea getAreaResultado() {
        return areaResultado;
    }

    public void setAreaResultado(JTextArea areaResultado) {
        this.areaResultado = areaResultado;
    }

    public JComboBox<String> getCboGet() {
        return cboGet;
    }

    public void setCboGet(JComboBox<String> cboGet) {
        this.cboGet = cboGet;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(JTextField txtId) {
        this.txtId = txtId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboGet = new javax.swing.JComboBox<>();
        btnConectar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaResultado = new javax.swing.JTextArea();
        txtId = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("URL: https://jsonplaceholder.typicode.com/ ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 0, -1, -1));

        jLabel2.setText("Recursos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel4.setText("Resultado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        cboGet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "posts", "comments", "albums", "photos", "todos", "users" }));
        cboGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGetActionPerformed(evt);
            }
        });
        getContentPane().add(cboGet, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 91, 31));

        btnConectar.setText("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 110, 60));

        areaResultado.setColumns(20);
        areaResultado.setRows(5);
        jScrollPane1.setViewportView(areaResultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 240, 160));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        try {
            this.getData();
        } catch (IOException ex) {
            Logger.getLogger(FrmPost.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConectarActionPerformed

    private void cboGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGetActionPerformed
        this.getGestorPosts().verificarItem();
    }//GEN-LAST:event_cboGetActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaResultado;
    private javax.swing.JButton btnConectar;
    private javax.swing.JComboBox<String> cboGet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
